"""
AUTO-FIX ENGINE (AstraDoctor 2.0)
Automatically repairs missing functions, missing exports,
bad imports, and UI renderer mismatches.
"""

import os
import re

# ----------------------------
# Utility: ensure file exists
# ----------------------------
def ensure_file_exists(path: str):
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write("# Auto-generated file\n")
        return True
    return False


# ----------------------------
# Create a missing function stub
# ----------------------------
def ensure_function_exists(path: str, func_name: str):
    with open(path, "r") as f:
        content = f.read()

    # If function already exists → OK
    if re.search(rf"def {func_name}\s*\(", content):
        return False

    # Add safe stub
    stub = f"""

# --- AUTO-GENERATED BY ASTRADOCTOR 2.0 ---
def {func_name}():
    import streamlit as st
    st.error("⚠ Auto-generated UI function: '{func_name}' was missing.")
    return None

"""

    with open(path, "a") as f:
        f.write(stub)

    return True


# ----------------------------
# Ensure __all__ export exists
# ----------------------------
def ensure_export(path: str, func_name: str):
    with open(path, "r") as f:
        content = f.read()

    # If no __all__ present, create it
    if "__all__" not in content:
        export_block = f"""

__all__ = [
    "{func_name}",
]
"""
        with open(path, "a") as f:
            f.write(export_block)
        return True

    # Append to existing __all__
    new_content = re.sub(
        r"__all__\s*=\s*\[([^\]]*)\]",
        lambda m: m.group(0).replace("]", f'    "{func_name}",\n]'),
        content
    )

    if new_content != content:
        with open(path, "w") as f:
            f.write(new_content)
        return True

    return False


# ----------------------------
# MASTER AUTO-FIX
# ----------------------------
def auto_fix_renderers():
    """
    Fixes:
    - render_dashboard
    - render_predictions
    - render_learning_center
    """

    ui_files = {
        "render_dashboard": "astra_modules/ui/tab_dashboard.py",
        "render_predictions": "astra_modules/ui/tab_predictions.py",
        "render_learning_center": "astra_modules/ui/tab_learning.py",
    }

    fixes = []

    for func, path in ui_files.items():
        if not os.path.exists(path):
            continue

        created = ensure_function_exists(path, func)
        exported = ensure_export(path, func)

        if created or exported:
            fixes.append(f"{func} patched in {path}")

    return fixes
