[theme]
base="light"
backgroundColor="#0B0E11"
secondaryBackgroundColor="#111827"
textColor="#E5E7EB"
primaryColor="#14B8A6"
font="sans serif"

[server]
headless=true
enableCORS=false

[browser]
gatherUsageStats=false

